### PR TITLE
Added /healthcheck

### PR DESCRIPTION
**Pull request by serge1peshcoff**
1. Added the /healthcheck endpoint
2. Added tests for it
3. Added docker healthcheck using it
4. Expose it (and only it) through traefik

### CODE REVIEW

**Comment by linuxbandit** [comment]
You have to add apk installing the package curl in the dockerfile

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by serge1peshcoff** [comment]
Done. I wonder why I forgot to do it earlier and how it was working on my machine (probably because each time I was installing curl inside the container locally to test lol)

**Comment by linuxbandit** [comment]
why a force-push now?

**Comment by serge1peshcoff** [comment]
Just didn't want to make a garbage commit for adding 1 word

**Pull request merged**
