### PR TITLE
feat(general): mail change template

### PR DESCRIPTION
**Pull request by serge1peshcoff**
Added mail change template for a new core.
1) a user requests a mail change
2) a MailChange object is created
3) it is sent to a user (in this new template)
4) user follows the link and confirms it
5) mail is changed
6) if the user didn't confirm it, then the email stays the same and MailChange object is deleted after some time (48h)

Bonus: `s/OMS/MyAEGEE` and every mail has MyAEGEE prefix now.

### CODE REVIEW

**Comment by serge1peshcoff** [comment]
@linuxbandit ping

**Comment by WikiRik** [comment]
@serge1peshcoff can this be merged?

**Comment by serge1peshcoff** [comment]
Yep, forgot about it

**Pull request merged**
